# Generated by Django 2.2.12 on 2020-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_barang', models.ImageField(null=True, upload_to='gambar/')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah_barang', models.PositiveIntegerField()),
                ('tanggal_barang', models.DateTimeField()),
            ],
        ),
    ]
