# Generated by Django 2.2.12 on 2020-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='tanggal_barang',
            field=models.DateField(auto_now_add=True),
        ),
    ]
